name: CI

on:
  push:
    branches: [ main ]

    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:
  build:
    name: 打包并上传

    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      - name: 读取并更新版本编号
        id: version

        run: |
          version=$(grep '^version=' ./module/module.prop | cut -d= -f2 | cut -d' ' -f1)
          echo "version=$version" >> $GITHUB_OUTPUT
          versionCode=$(grep '^versionCode=' ./module/module.prop | cut -d= -f2)
          versionCode=$((versionCode + 1))
          version="$version (${versionCode})"
          sed -i "s/^version=.*/version=$version/" ./module/module.prop
          sed -i "s/^versionCode=.*/versionCode=$versionCode/" ./module/module.prop

      - name: 推送更改至仓库
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./module/module.prop
          git commit -m "chore: 更新 versionCode"
          git push origin main

      - name: 组装模块
        run: |
          mkdir -p ./pack
          cp -r ./module/* ./pack
          cp -r ./script ./pack
          cp ./install.sh ./pack/customize.sh
          cd ./pack
          zip -r9 ../${{ github.event.repository.name }}_${{ steps.version.outputs.version }}.zip .

      - name: 上传
        uses: actions/upload-artifact@v4

        with:
          name: ${{ github.event.repository.name }}_${{ steps.version.outputs.version }}

          path: |
            ./pack/*

      - name: 推送到Telegram CI 频道
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

          MESSAGE: ${{ github.event.head_commit.message }}

          CI: ./*.zip

        run: |
          curl "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGrop?chat_id=@hiruocha_ci&media=%5B%7B%22type%22%3A%22document%22%2C%22media%22%3A%22attach%3A%2F%2Fci%22%2C%22caption%22%3A%24%7BMESSAGE%7D%7D%5D" -F ci="@${CI}"